[launcher]
author=API Connect
description=GUI wizard per la creazione di Modular Input che interrogano API REST esterne, con parsing visuale della risposta e mapping al tracciato standard aziendale.
version=1.0.0

[package]
id=api_connect
check_for_updates=false

[ui]
is_visible=true
label=API Connect

[install]
is_configured=false
build=1
