[api_connect_events]
search = sourcetype=api_connect:*
priority = 1
disabled = 0

[api_connect_logger]
search = index=_internal sourcetype=custom_script_logger source=api_connect:*
priority = 1
disabled = 0

[api_connect_error]
search = index=_internal sourcetype=custom_script_logger source=api_connect:* level=ERROR
priority = 2
disabled = 0
