# props.conf — API Connect
# Sourcetype base per tutti gli eventi generati dagli input API Connect.

[api_connect]
SHOULD_LINEMERGE  = false
LINE_BREAKER      = ([\r\n]+)
TIME_PREFIX       = time=
TIME_FORMAT       = %s
MAX_TIMESTAMP_LOOKAHEAD = 20
KV_MODE           = auto
ANNOTATE_PUNCT    = false

# Sourcetype per il logger di esecuzione script
[custom_script_logger]
SHOULD_LINEMERGE  = false
LINE_BREAKER      = ([\r\n]+)
KV_MODE           = auto
ANNOTATE_PUNCT    = false
