# restmap.conf v2 — API Connect
# Espone gli endpoint REST custom.

[admin:api_connect]
match   = /api_connect
members = api_connect_inputs, api_connect_test, api_connect_generate

[admin_external:api_connect_inputs]
handlertype           = python
python.version        = python3
handlerfile           = api_connect_rest.py
handleractions        = list, create, edit, remove
handlerpersistentmode = false

[admin_external:api_connect_test]
handlertype           = python
python.version        = python3
handlerfile           = api_connect_rest.py
handleractions        = create
handlerpersistentmode = false

[admin_external:api_connect_generate]
handlertype           = python
python.version        = python3
handlerfile           = api_connect_generate.py
handleractions        = create
handlerpersistentmode = false
