[eventtype=api_connect_events]
api_connect = enabled
custom_input = enabled

[eventtype=api_connect_logger]
api_connect = enabled
log = enabled

[eventtype=api_connect_error]
api_connect = enabled
error = enabled
