[api_connect_inputs_lookup]
external_type = kvstore
collection = api_connect_inputs
fields_list = _key, name, label, auth_type, credential_realm, endpoint_url, method, headers, body, pagination_type, chain_calls, parsing_config, field_mapping, index, sourcetype, source, schedule, logger_source, enabled, last_status, last_run, last_count, last_latency_ms
